draw_set_alpha(1)
draw_set_font(global.thenfont)
draw_set_halign(fa_left)
draw_set_color(c_white)
draw_window(__view_get( e__VW.XView, 0 )+72+v_offset,__view_get( e__VW.YView, 0 )+32,30,19)
draw_window(__view_get( e__VW.XView, 0 )+72+v_offset,__view_get( e__VW.YView, 0 )+8,7,3)
draw_window(__view_get( e__VW.XView, 0 )+72+v_offset,__view_get( e__VW.YView, 0 )+192,30,5)
draw_window(__view_get( e__VW.XView, 0 )+8+v_offset,__view_get( e__VW.YView, 0 )+8,8,4)
draw_text(__view_get( e__VW.XView, 0 )+20+v_offset,__view_get( e__VW.YView, 0 )+18,string_hash_to_newline("Checkout"))

draw_text(_x[1],__view_get( e__VW.YView, 0 )+14,string_hash_to_newline("Page "+string(page+1)))
draw_text(_x[1],_y[1],string_hash_to_newline(global.item[(storage[1]>0 ? storage[1] : 0),1]))
draw_text(_x[2],_y[1],string_hash_to_newline(global.item[(storage[2]>0 ? storage[2] : 0),1]))
draw_text(_x[1],_y[2],string_hash_to_newline(global.item[(storage[3]>0 ? storage[3] : 0),1]))
draw_text(_x[2],_y[2],string_hash_to_newline(global.item[(storage[4]>0 ? storage[4] : 0),1]))
draw_text(_x[1],_y[3],string_hash_to_newline(global.item[(storage[5]>0 ? storage[5] : 0),1]))
draw_text(_x[2],_y[3],string_hash_to_newline(global.item[(storage[6]>0 ? storage[6] : 0),1]))
draw_text(_x[1],_y[4],string_hash_to_newline(global.item[(storage[7]>0 ? storage[7] : 0),1]))
draw_text(_x[2],_y[4],string_hash_to_newline(global.item[(storage[8]>0 ? storage[8] : 0),1]))
draw_text(_x[1],_y[5],string_hash_to_newline(global.item[(storage[9]>0 ? storage[9] : 0),1]))
draw_text(_x[2],_y[5],string_hash_to_newline(global.item[(storage[10]>0 ? storage[10] : 0),1]))
draw_text(_x[1],_y[6],string_hash_to_newline(global.item[(storage[11]>0 ? storage[11] : 0),1]))
draw_text(_x[2],_y[6],string_hash_to_newline(global.item[(storage[12]>0 ? storage[12] : 0),1]))
draw_text(_x[1],_y[7],string_hash_to_newline(global.item[(storage[13]>0 ? storage[13] : 0),1]))
draw_text(_x[2],_y[7],string_hash_to_newline(global.item[(storage[14]>0 ? storage[14] : 0),1]))
draw_text(_x[1],_y[8],string_hash_to_newline(global.item[(storage[15]>0 ? storage[15] : 0),1]))
draw_text(_x[2],_y[8],string_hash_to_newline(global.item[(storage[16]>0 ? storage[16] : 0),1]))
draw_text(_x[1],_y[9],string_hash_to_newline(global.item[(storage[17]>0 ? storage[17] : 0),1]))
draw_text(_x[2],_y[9],string_hash_to_newline(global.item[(storage[18]>0 ? storage[18] : 0),1]))
draw_text(_x[1],_y[10],string_hash_to_newline(global.item[(storage[19]>0 ? storage[19] : 0),1]))
draw_text(_x[2],_y[10],string_hash_to_newline(global.item[(storage[20]>0 ? storage[20] : 0),1]))

draw_text(_x[1],y+199,string_hash_to_newline(global.item[(num>0 ? num : 0),2]))

draw_sprite(spr_cursor,cursor_image_index,cursor_x-3,cursor_y+8)

